var numOne = document.getElementById('length');
var numTwo = document.getElementById('width');
var addSum = document.getElementById('add-sum');
var expAns = document.getElementById('e');
numOne.addEventListener('input', add);
numTwo.addEventListener('input', add);
function add() {
var one = parseFloat(numOne.value) || 0;
var two = parseFloat(numTwo.value) || 0;
var final = one * two;
addSum.innerText = final * 1;
expAns.innerText = ("The area of the object is " + final + " square units");
}